### ISSUE TITLE
camelify affecting -= operator

### ISSUE THREAD

**Issue by raymond-w-ko** [anko/eslisp-camelify#3]
```
$ eslc -t eslisp-camelify
> (-= y x)
evalmachine.<anonymous>:1
y = x;
    ^
ReferenceError: x is not defined
    at evalmachine.<anonymous>:1:5
    at Object.exports.runInThisContext (vm.js:54:17)
    at REPLServer.repl.start.eval (/home/rko/npm-global/lib/node_modules/eslisp/lib/cli.js:163:36)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:90:13)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
>
```

The equals sign seems to fails the camel case process and be removed?

**Comment by anko** [comment]
These issues you're finding (like https://github.com/anko/eslisp-propertify/issues/3 too) illustrate well why I want reader macros in eslisp (https://github.com/anko/eslisp/issues/24) to replace transform macros. It's easier to make the _parser_ catch the edge cases and weird interactions than doing it after parsing like this…

Either way, this is fixed in 0.3.0 for now: dashes at the start and end of _anything_ are preserved.

Thanks again! :sparkles:
